//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct AndroidKeystoreFileCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "AndroidKeystoreFile",
        abstract: "",
        subcommands: [
            AndroidKeystoreFileCreateCommand.self,
            AndroidKeystoreFileListCommand.self
        ]
        // defaultSubcommand: AppListCommand.self
    )
}