//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Add a new Android keystore file to an app
struct AndroidKeystoreFileCreateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AndroidKeystoreFileCreate",
        abstract: "Create an Android keystore file"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String

    func run() throws {
        let request = API.AndroidKeystoreFile.AndroidKeystoreFileCreate.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}