//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all the Bitrise builds that can be accessed with the authenticated account. Filter builds based on their owner, using the owner slug, or the status of the build.
struct BuildListAllCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildListAll",
        abstract: "List all builds"
    )

    @Option var ownerSlug: String?
    @Option var isOnHold: Bool?
    @Option var status: Int?
    @Option var next: String?
    @Option var limit: Int?

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.Builds.BuildListAll.Request(ownerSlug: ownerSlug, isOnHold: isOnHold, status: status, next: next, limit: limit)

        client
            .call(request)
            .waitUntilDone()
    }
}