//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List the workflows that were triggered at any time for a given Bitrise app. Note that it might list workflows that are currently not defined in the app's `bitrise.yml` configuration - and conversely, workflows that were never triggered will not be listed even if they are defined in the `bitrise.yml` file.
struct BuildWorkflowListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildWorkflowList",
        abstract: "List the workflows of an app"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.Builds.BuildWorkflowList.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}