//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all available avatar candidates for an application
struct AvatarCandidateListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "AvatarCandidateList",
        abstract: "Get list of the avatar candidates"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.AvatarCandidate.AvatarCandidateList.Request(appSlug: appSlug))
//            .await()
            .waitUntilDone()
    }
}