//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Promotes an avatar candidate for an app
struct AvatarCandidatePromoteCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AvatarCandidatePromote",
        abstract: "Promote an avatar candidate"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var avatarSlug: String

    func run() throws {
        let request = API.AvatarCandidate.AvatarCandidatePromote.Request(appSlug: appSlug, avatarSlug: avatarSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}