//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Add new avatar candidates to a specific app
struct AvatarCandidateCreateCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "AvatarCandidateCreate",
        abstract: "Create avatar candidates"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.AvatarCandidate.AvatarCandidateCreate.Request(appSlug: appSlug))
//            .await()
            .waitUntilDone()
    }
}