//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Add new avatar candidates to a specific app
struct AvatarCandidateCreateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AvatarCandidateCreate",
        abstract: "Create avatar candidates"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String

    func run() throws {
        let request = API.AvatarCandidate.AvatarCandidateCreate.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}