//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all the available Bitrise addons
struct AddonsListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "AddonsList",
        abstract: "Get list of available Bitrise addons"
    )


    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.Addons.AddonsList.Request())
//            .await()
            .waitUntilDone()
    }
}