//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Show details of a specific Bitrise addon
struct AddonsShowCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AddonsShow",
        abstract: "Get a specific Bitrise addon"
    )

    @Argument var addonId: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.Addons.AddonsShow.Request(addonId: addonId)

        client
            .call(request)
            .waitUntilDone()
    }
}