//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all the provisioned addons for organization
struct AddonListByOrganizationCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "AddonListByOrganization",
        abstract: "Get list of the addons for organization"
    )

    @Argument var organizationSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.Addons.AddonListByOrganization.Request(organizationSlug: organizationSlug))
//            .await()
            .waitUntilDone()
    }
}