//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Update a specific build request of a specific app
struct BuildRequestUpdateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildRequestUpdate",
        abstract: "Update a build request"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var buildRequestSlug: String
    @Argument var body: V0BuildRequestUpdateArguments

    func run() throws {
        let request = Bitrise.BuildRequest.BuildRequestUpdate.Request(appSlug: appSlug, buildRequestSlug: buildRequestSlug, body: body.data!)

        client
            .call(request)
            .waitUntilDone()
    }
}

