//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List registered test devices of all members of a specified Bitrise app
struct TestDeviceListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "TestDeviceList",
        abstract: "List the test devices for an app"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String

    func run() throws {
        let request = API.TestDevices.TestDeviceList.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}