//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Get the specified build of a given Bitrise app. You need to provide both an app slug and a build slug. You can get the build slug either by calling the [/builds](https://api-docs.bitrise.io/#/builds/build-list) endpoint or by clicking on the build on bitrise.io and copying the slug from the URL. The endpoint returns all the relevant data of the build.
struct BuildShowCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildShow",
        abstract: "Get a build of a given app"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var buildSlug: String

    func run() throws {
        let request = Bitrise.Builds.BuildShow.Request(appSlug: appSlug, buildSlug: buildSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

