//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct AppleApiCredentialsCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppleApiCredentials",
        abstract: "",
        subcommands: [
            AppleApiCredentialListCommand.self
        ]
        // defaultSubcommand: AppListCommand.self
    )
}