//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Re-deliver the delivery item of a specified webhook of a Bitrise application
struct WebhookDeliveryItemRedeliverCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "WebhookDeliveryItemRedeliver",
        abstract: "Re-deliver the webhook delivery items of an app"
    )

    @Argument var appSlug: String
    @Argument var appWebhookSlug: String
    @Argument var webhookDeliveryItemSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.WebhookDeliveryItem.WebhookDeliveryItemRedeliver.Request(appSlug: appSlug, appWebhookSlug: appWebhookSlug, webhookDeliveryItemSlug: webhookDeliveryItemSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}