//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Delete an existing outgoing webhook for a specified Bitrise app.
struct OutgoingWebhookDeleteCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "OutgoingWebhookDelete",
        abstract: "Delete an outgoing webhook of an app"
    )

    @Argument var appSlug: String
    @Argument var appWebhookSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.OutgoingWebhook.OutgoingWebhookDelete.Request(appSlug: appSlug, appWebhookSlug: appWebhookSlug))
//            .await()
            .waitUntilDone()
    }
}