//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Update an existing outgoing webhook (URL, events, secrets and headers) for a specified Bitrise app. Even if you do not want to change one of the parameters, you still have to provide that parameter as well: simply use its existing value.
struct OutgoingWebhookUpdateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "OutgoingWebhookUpdate",
        abstract: "Update an outgoing webhook of an app"
    )

    @Argument var appSlug: String
    @Argument var appWebhookSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.OutgoingWebhook.OutgoingWebhookUpdate.Request(appSlug: appSlug, appWebhookSlug: appWebhookSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}