//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

struct AuthOptions: ParsableArguments {
    @Option var addonAuthToken: String?
    @Option var personalAccessToken: String?
}