//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List the existing open build requests of a specified Bitrise app
struct BuildRequestListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildRequestList",
        abstract: "List the open build requests for an app"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String

    func run() throws {
        let request = API.BuildRequest.BuildRequestList.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

