//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Add an SSH-key to a specific app. After creating an app, you need to register the SSH key so that Bitrise will be able to access and clone your repository during the build process. This requires the app slug of your newly created app.
struct SshKeyCreateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "SshKeyCreate",
        abstract: "Add an SSH-key to a specific app"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var body: V0SSHKeyUploadArguments

    func run() throws {
        let request = Bitrise.AppSetup.SshKeyCreate.Request(appSlug: appSlug, body: body.data!)

        client
            .call(request)
            .waitUntilDone()
    }
}

