//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// List all the available apps owned by a given organization. [Find the organization URL](https://devcenter.bitrise.io/team-management/organizations/org-url/) of the organisations you are part of; be aware that the endpoint will not return any apps if the authenticated account is not a member of the given organisation.
struct AppListByOrganizationCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppListByOrganization",
        abstract: "Get list of the apps for an organization"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var orgSlug: String
    @Option var sortBy: Bitrise.Application.AppListByOrganization.SortBy?
    @Option var next: String?
    @Option var limit: Int?

    func run() throws {
        let request = Bitrise.Application.AppListByOrganization.Request(orgSlug: orgSlug, sortBy: sortBy, next: next, limit: limit)

        client
            .call(request)
            .waitUntilDone()
    }
}

extension Bitrise.Application.AppListByOrganization.SortBy: ExpressibleByArgument { }
