//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all Bitrise organizations that the user is part of
struct OrgListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "OrgList",
        abstract: "List the organizations that the user is part of"
    )


    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.Organizations.OrgList.Request())
//            .await()
            .waitUntilDone()
    }
}