//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Get a specified Bitrise organization that the user is part of.
struct OrgShowCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "OrgShow",
        abstract: "Get a specified organization."
    )

    @Argument var orgSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.Organizations.OrgShow.Request(orgSlug: orgSlug))
//            .await()
            .waitUntilDone()
    }
}