//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// List all the android keystore files that have been uploaded to a specific app.
struct AndroidKeystoreFileListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AndroidKeystoreFileList",
        abstract: "Get a list of the android keystore files"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Option var next: String?
    @Option var limit: Int?

    func run() throws {
        let request = Bitrise.AndroidKeystoreFile.AndroidKeystoreFileList.Request(appSlug: appSlug, next: next, limit: limit)

        client
            .call(request)
            .waitUntilDone()
    }
}

