//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List the existing open build requests of a specified Bitrise app
struct BuildRequestListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildRequestList",
        abstract: "List the open build requests for an app"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.BuildRequest.BuildRequestList.Request(appSlug: appSlug))
//            .await()
            .waitUntilDone()
    }
}