//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Update a specific build request of a specific app
struct BuildRequestUpdateCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildRequestUpdate",
        abstract: "Update a build request"
    )

    @Argument var appSlug: String
    @Argument var buildRequestSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.BuildRequest.BuildRequestUpdate.Request(appSlug: appSlug, buildRequestSlug: buildRequestSlug))
//            .await()
            .waitUntilDone()
    }
}