//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct BuildRequestCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildRequest",
        abstract: "",
        subcommands: [
            BuildRequestListCommand.self,
            BuildRequestUpdateCommand.self
        ]
        // defaultSubcommand: AppListCommand.self
    )
}