//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Update a specific build request of a specific app
struct BuildRequestUpdateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildRequestUpdate",
        abstract: "Update a build request"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var buildRequestSlug: String

    func run() throws {
        let request = API.BuildRequest.BuildRequestUpdate.Request(appSlug: appSlug, buildRequestSlug: buildRequestSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}