//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct TestDevicesCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "TestDevices",
        abstract: "",
        subcommands: [
            TestDeviceListCommand.self
        ]
    )
}