//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//
// Template used API+CLI
// https://github.com/csjones/SwagGen-templates
//

import Foundation

public class AddonsSetupInstruction: APIModel {

    public var cardContent: String?

    public var description: String?

    public var type: String?

    public init(cardContent: String? = nil, description: String? = nil, type: String? = nil) {
        self.cardContent = cardContent
        self.description = description
        self.type = type
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        cardContent = try container.decodeIfPresent("card_content")
        description = try container.decodeIfPresent("description")
        type = try container.decodeIfPresent("type")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(cardContent, forKey: "card_content")
        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(type, forKey: "type")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AddonsSetupInstruction else { return false }
      guard self.cardContent == object.cardContent else { return false }
      guard self.description == object.description else { return false }
      guard self.type == object.type else { return false }
      return true
    }

    public static func == (lhs: AddonsSetupInstruction, rhs: AddonsSetupInstruction) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
