//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//
// Template used API+CLI
// https://github.com/csjones/SwagGen-templates
//

import Foundation

public class V0AndroidKeystoreFileUploadParams: APIModel {

    public var alias: String

    public var password: String

    public var privateKeyPassword: String

    public var uploadFileName: String

    public var uploadFileSize: Int

    public init(alias: String, password: String, privateKeyPassword: String, uploadFileName: String, uploadFileSize: Int) {
        self.alias = alias
        self.password = password
        self.privateKeyPassword = privateKeyPassword
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        alias = try container.decode("alias")
        password = try container.decode("password")
        privateKeyPassword = try container.decode("private_key_password")
        uploadFileName = try container.decode("upload_file_name")
        uploadFileSize = try container.decode("upload_file_size")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(alias, forKey: "alias")
        try container.encode(password, forKey: "password")
        try container.encode(privateKeyPassword, forKey: "private_key_password")
        try container.encode(uploadFileName, forKey: "upload_file_name")
        try container.encode(uploadFileSize, forKey: "upload_file_size")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0AndroidKeystoreFileUploadParams else { return false }
      guard self.alias == object.alias else { return false }
      guard self.password == object.password else { return false }
      guard self.privateKeyPassword == object.privateKeyPassword else { return false }
      guard self.uploadFileName == object.uploadFileName else { return false }
      guard self.uploadFileSize == object.uploadFileSize else { return false }
      return true
    }

    public static func == (lhs: V0AndroidKeystoreFileUploadParams, rhs: V0AndroidKeystoreFileUploadParams) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
