//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//
// Template used API+CLI
// https://github.com/csjones/SwagGen-templates
//

import Foundation

public typealias V0AvatarCandidateCreateResponseItems = [V0AvatarCandidateCreateResponseItem]
