//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct BitriseCLICommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "BitriseCLI",
        abstract: "Official REST API for Bitrise.io",
        subcommands: [
            ActivityCommand.self,
            AddonsCommand.self,
            AndroidKeystoreFileCommand.self,
            AppSetupCommand.self,
            AppleApiCredentialsCommand.self,
            ApplicationCommand.self,
            AvatarCandidateCommand.self,
            BuildArtifactCommand.self,
            BuildCertificateCommand.self,
            BuildRequestCommand.self,
            BuildsCommand.self,
            GenericProjectFileCommand.self,
            OrganizationsCommand.self,
            OutgoingWebhookCommand.self,
            ProvisioningProfileCommand.self,
            TestDevicesCommand.self,
            UserCommand.self,
            WebhookDeliveryItemCommand.self
        ]
    )
}