//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Retrieve data of a specific build certificate. You can fetch the build certificate slug for this endpoint if you first call the [GET /apps/{app-slug}/build-certificates](https://api-docs.bitrise.io/#/build-certificate/build-certificate-list) endpoint to list all available build certificates of an app. Read more in our [Getting a specific iOS code signing file's data](https://devcenter.bitrise.io/api/managing-ios-code-signing-files/#getting-a-specific-ios-code-signing-files-data) guide.
struct BuildCertificateShowCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildCertificateShow",
        abstract: "Get a specific build certificate"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var buildCertificateSlug: String

    func run() throws {
        let request = Bitrise.BuildCertificate.BuildCertificateShow.Request(appSlug: appSlug, buildCertificateSlug: buildCertificateSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

