//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// List all the outgoing webhooks registered for a specified Bitrise app. This returns all the relevant data of the webhook, including the slug of the webhook and its URL.
struct OutgoingWebhookListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "OutgoingWebhookList",
        abstract: "List the outgoing webhooks of an app"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Option var next: String?
    @Option var limit: Int?

    func run() throws {
        let request = Bitrise.OutgoingWebhook.OutgoingWebhookList.Request(appSlug: appSlug, next: next, limit: limit)

        client
            .call(request)
            .waitUntilDone()
    }
}

