//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Shows the authenticated users profile data
struct UserProfileCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "UserProfile",
        abstract: "Get your profile data"
    )


    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.User.UserProfile.Request())
//            .await()
            .waitUntilDone()
    }
}