//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Get the subscription of the user: the current plan, any pending plans, and the duration of a trial period if applicable
struct UserPlanCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "UserPlan",
        abstract: "The subscription plan of the user"
    )


    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.User.UserPlan.Request())
//            .await()
            .waitUntilDone()
    }
}