//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

struct AvatarCandidateCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "AvatarCandidate",
        abstract: "",
        subcommands: [
            AvatarCandidateCreateCommand.self,
            AvatarCandidateListCommand.self,
            AvatarCandidatePromoteCommand.self
        ]
    )
}