//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Add new avatar candidates to a specific app
struct AvatarCandidateCreateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AvatarCandidateCreate",
        abstract: "Create avatar candidates"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var body: V0AvatarCandidateCreateBulkArguments

    func run() throws {
        let request = Bitrise.AvatarCandidate.AvatarCandidateCreate.Request(appSlug: appSlug, body: body.data!)

        client
            .call(request)
            .waitUntilDone()
    }
}

