//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct GenericProjectFileCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "GenericProjectFile",
        abstract: "",
        subcommands: [
            GenericProjectFileConfirmCommand.self,
            GenericProjectFileDeleteCommand.self,
            GenericProjectFileListCommand.self,
            GenericProjectFileShowCommand.self,
            GenericProjectFileUpdateCommand.self,
            GenericProjectFilesCreateCommand.self,
        ]
        // defaultSubcommand: AppListCommand.self
    )
}