//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// List all the Bitrise activity events
struct ActivityListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "ActivityList",
        abstract: "Get list of Bitrise activity events"
    )

    @OptionGroup var auth: AuthOptions
    @Option var next: String?
    @Option var limit: Int?

    func run() throws {
        let request = Bitrise.Activity.ActivityList.Request(next: next, limit: limit)

        client
            .call(request)
            .waitUntilDone()
    }
}

