//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

struct ActivityCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "Activity",
        abstract: "",
        subcommands: [
            ActivityListCommand.self
        ]
    )
}