//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Update the `is_public_page_enabled` attribute of your app's build. The required parameters are app slug, build slug and artifact slug. You can fetch the build artifact slug if you first list all build artifacts of an app with the [GET /apps/](https://api-docs.bitrise.io/#/build-artifact/artifact-list) endpoint.
struct ArtifactUpdateCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "ArtifactUpdate",
        abstract: "Update a build artifact"
    )

    @Argument var appSlug: String
    @Argument var buildSlug: String
    @Argument var artifactSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.BuildArtifact.ArtifactUpdate.Request(appSlug: appSlug, buildSlug: buildSlug, artifactSlug: artifactSlug))
//            .await()
            .waitUntilDone()
    }
}