//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Delete a build artifact of an app's build. The required parameters are app slug, build slug and artifact slug. You can fetch the build artifact slug if you first list all build artifacts of an app with the [/apps/](https://api-docs.bitrise.io/#/build-artifact/artifact-list) endpoint.
struct ArtifactDeleteCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "ArtifactDelete",
        abstract: "Delete a build artifact"
    )

    @Argument var appSlug: String
    @Argument var buildSlug: String
    @Argument var artifactSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.BuildArtifact.ArtifactDelete.Request(appSlug: appSlug, buildSlug: buildSlug, artifactSlug: artifactSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}