//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct BuildArtifactCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildArtifact",
        abstract: "",
        subcommands: [
            ArtifactDeleteCommand.self,
            ArtifactListCommand.self,
            ArtifactShowCommand.self,
            ArtifactUpdateCommand.self
        ]
        // defaultSubcommand: AppListCommand.self
    )
}