//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// This is the last step of uploading a generic project file to Bitrise. Confirm the generic project file upload and view the file on the Code Signing tab of a specific app. Read more in our [Confirming the upload](https://devcenter.bitrise.io/api/managing-files-in-generic-file-storage/#confirming-the-file-upload) guide.
struct GenericProjectFileConfirmCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "GenericProjectFileConfirm",
        abstract: "Confirm a generic project file upload"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var genericProjectFileSlug: String

    func run() throws {
        let request = Bitrise.GenericProjectFile.GenericProjectFileConfirm.Request(appSlug: appSlug, genericProjectFileSlug: genericProjectFileSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

