//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Retrieve data of a specific generic project file to check its attributes and optionally modify them with the [PATCH /apps/](https://api-docs.bitrise.io/#/generic-project-file/generic-project-file-update) endpoint. Read more in our [Retrieving a specific file's data](https://devcenter.bitrise.io/api/managing-files-in-generic-file-storage/#retrieving-a-specific-files-data) guide.
struct GenericProjectFileShowCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "GenericProjectFileShow",
        abstract: "Get a specific generic project file"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var genericProjectFileSlug: String

    func run() throws {
        let request = Bitrise.GenericProjectFile.GenericProjectFileShow.Request(appSlug: appSlug, genericProjectFileSlug: genericProjectFileSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

