//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Delete an app's build certificate. You can fetch the build certificate slug for this endpoint if you first call the [GET /apps/{app-slug}/build-certificates](https://api-docs.bitrise.io/#/build-certificate/build-certificate-list) endpoint to list all available build certificates of an app. Read more in our [Deleting an iOS code signing file](https://devcenter.bitrise.io/api/managing-ios-code-signing-files/#deleting-an-ios-code-signing-file) guide.
struct BuildCertificateDeleteCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildCertificateDelete",
        abstract: "Delete a build certificate"
    )

    @Argument var appSlug: String
    @Argument var buildCertificateSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.BuildCertificate.BuildCertificateDelete.Request(appSlug: appSlug, buildCertificateSlug: buildCertificateSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}