//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Upload a new bitrise.yml for your application.
struct AppConfigCreateCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppConfigCreate",
        abstract: "Upload a new bitrise.yml for your application."
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String

    func run() throws {
        let request = API.AppSetup.AppConfigCreate.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}