//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Upload a new bitrise.yml for your application.
struct AppConfigCreateCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppConfigCreate",
        abstract: "Upload a new bitrise.yml for your application."
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.AppSetup.AppConfigCreate.Request(appSlug: appSlug))
//            .await()
            .waitUntilDone()
    }
}