//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Save the application after registering it on Bitrise and registering an SSH key (and, optionally, adding a webhook). With this endpoint you can define the initial configuration, define application-level environment variables, determine the project type, and set an Organization to be the owner of the app. Read more about the app registration process in our [detailed guide](https://devcenter.bitrise.io/api/adding-and-managing-apps/#adding-a-new-app).
struct AppFinishCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppFinish",
        abstract: "Save the application at the end of the app registration process"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.AppSetup.AppFinish.Request(appSlug: appSlug))
//            .await()
            .waitUntilDone()
    }
}