//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct AppSetupCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppSetup",
        abstract: "",
        subcommands: [
            AppConfigCreateCommand.self,
            AppCreateCommand.self,
            AppFinishCommand.self,
            AppWebhookCreateCommand.self,
            SshKeyCreateCommand.self,
        ]
        // defaultSubcommand: AppListCommand.self
    )
}