//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Add an SSH-key to a specific app. After creating an app, you need to register the SSH key so that Bitrise will be able to access and clone your repository during the build process. This requires the app slug of your newly created app.
struct SshKeyCreateCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "SshKeyCreate",
        abstract: "Add an SSH-key to a specific app"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.AppSetup.SshKeyCreate.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}