//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

struct AddonsCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "Addons",
        abstract: "",
        subcommands: [
            AddonListByAppCommand.self,
            AddonListByOrganizationCommand.self,
            AddonListByUserCommand.self,
            AddonsListCommand.self,
            AddonsShowCommand.self
        ]
    )
}