//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// List all the provisioned addons for organization
struct AddonListByOrganizationCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AddonListByOrganization",
        abstract: "Get list of the addons for organization"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var organizationSlug: String

    func run() throws {
        let request = Bitrise.Addons.AddonListByOrganization.Request(organizationSlug: organizationSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

