//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all the apps available for the authenticated account, including those that are owned by other users or Organizations.
struct AppListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppList",
        abstract: "Get list of the apps"
    )

    @Option var sortBy: SortBy?
    @Option var next: String?
    @Option var limit: Int?

    @OptionGroup var auth: AuthOptions

    func run() throws {
        let request = API.Application.AppList.Request(sortBy: sortBy, next: next, limit: limit)

        client
            .call(request)
            .waitUntilDone()
    }
}