//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List the existing branches of the repository of a specified Bitrise app.
struct BranchListCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BranchList",
        abstract: "List the branches of an app's repository"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String

    func run() throws {
        let request = API.Application.BranchList.Request(appSlug: appSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}