//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List the existing branches of the repository of a specified Bitrise app.
struct BranchListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "BranchList",
        abstract: "List the branches of an app's repository"
    )

    @Argument var appSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.Application.BranchList.Request(appSlug: appSlug))
//            .await()
            .waitUntilDone()
    }
}