//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// This is the last step of the upload process. Confirm the provisioning profile upload and view the file on the Code Signing tab of a specific app. Read more in our [Confirming the iOS code signing file upload](https://devcenter.bitrise.io/api/managing-ios-code-signing-files/#confirming-the-ios-code-signing-file-upload) guide.
struct ProvisioningProfileConfirmCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "ProvisioningProfileConfirm",
        abstract: "Confirm a provisioning profile upload"
    )

    @Argument var appSlug: String
    @Argument var provisioningProfileSlug: String

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.ProvisioningProfile.ProvisioningProfileConfirm.Request(appSlug: appSlug, provisioningProfileSlug: provisioningProfileSlug))
//            .await()
            .waitUntilDone()
    }
}