//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// This is the last step of the upload process. Confirm the provisioning profile upload and view the file on the Code Signing tab of a specific app. Read more in our [Confirming the iOS code signing file upload](https://devcenter.bitrise.io/api/managing-ios-code-signing-files/#confirming-the-ios-code-signing-file-upload) guide.
struct ProvisioningProfileConfirmCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "ProvisioningProfileConfirm",
        abstract: "Confirm a provisioning profile upload"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var provisioningProfileSlug: String

    func run() throws {
        let request = API.ProvisioningProfile.ProvisioningProfileConfirm.Request(appSlug: appSlug, provisioningProfileSlug: provisioningProfileSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}