//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// Get the bitrise.yml file of one of the builds of a given app. This will return the `bitrise.yml` configuration with which the build ran. You can compare it to [the current bitrise.yml configuration](https://api-docs.bitrise.io/#/application/app-config-datastore-show) of the app.
struct BuildBitriseYmlShowCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "BuildBitriseYmlShow",
        abstract: "Get the bitrise.yml of a build"
    )

    @OptionGroup var auth: AuthOptions
    @Argument var appSlug: String
    @Argument var buildSlug: String

    func run() throws {
        let request = API.Builds.BuildBitriseYmlShow.Request(appSlug: appSlug, buildSlug: buildSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

