//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct BuildsCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "Builds",
        abstract: "",
        subcommands: [
            BuildAbortCommand.self,
            BuildBitriseYmlShowCommand.self,
            BuildListCommand.self,
            BuildListAllCommand.self,
            BuildLogCommand.self,
            BuildShowCommand.self,
            BuildTriggerCommand.self,
            BuildWorkflowListCommand.self
        ]
    )
}