//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

struct AppleApiCredentialsCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "AppleApiCredentials",
        abstract: "",
        subcommands: [
            AppleApiCredentialListCommand.self
        ]
    )
}