//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

struct ActivityCommand: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "Activity",
        abstract: "",
        subcommands: [
            ActivityListCommand.self,
        ]
        // defaultSubcommand: AppListCommand.self
    )
}