//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

// List all the Bitrise activity events
struct ActivityListCommand: AuthenticatedClientCommand {
    static var configuration = CommandConfiguration(
        commandName: "ActivityList",
        abstract: "Get list of Bitrise activity events"
    )

    @Option var next: String?
    @Option var limit: Int?

    @OptionGroup var auth: AuthOptions

    func run() throws {
        client
            .call(API.Activity.ActivityList.Request(next: next, limit: limit))
//            .await()
            .waitUntilDone()
    }
}