//
// Bitrise app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import API

// Get a specified Bitrise organization that the user is part of.
struct OrgShowCommand: AuthenticatedCommand {
    static var configuration = CommandConfiguration(
        commandName: "OrgShow",
        abstract: "Get a specified organization."
    )

    @OptionGroup var auth: AuthOptions
    @Argument var orgSlug: String

    func run() throws {
        let request = Bitrise.Organizations.OrgShow.Request(orgSlug: orgSlug)

        client
            .call(request)
            .waitUntilDone()
    }
}

