//
// BitriseCLI app generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import ArgumentParser
import BitriseAPI

protocol AuthenticatedCommand: ParsableCommand {
    var auth: AuthOptions { get }
    var client: APIClient { get }
}

extension AuthenticatedCommand {
    var client: APIClient {
        if let personalAccessToken = auth.personalAccessToken {
            APIClient.default.defaultHeaders["Authorization"] = personalAccessToken
        }

        if let addonAuthToken = auth.addonAuthToken {
            APIClient.default.defaultHeaders["Bitrise-Addon-Auth-Token"] = addonAuthToken
        }

        return APIClient.default
    }
}